import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

import numpy as np
from manim import *
from manim_voiceover import VoiceoverScene

from tts import get_speech_service
from common import TRAIN_COLOR, VALIDATION_COLOR


class Scene06Mixin:
    # ------------------------------------------------------------------
    # Scene 6: why training-validation split works -- training error vs.
    # validation error across polynomial degree, with a U-shaped
    # validation minimum at degree 3 while training error keeps falling
    # ------------------------------------------------------------------
    @staticmethod
    def scene6_true_fn(x):
        return 0.15 * x**3 - 0.4 * x**2 - 0.6 * x + 2

    @staticmethod
    def scene6_data():
        rng = np.random.default_rng(107)
        n = 20
        x = np.sort(rng.uniform(-3, 3, n))
        y = Scene06Mixin.scene6_true_fn(x) + rng.normal(0, 0.6, n)
        idx = rng.permutation(n)
        n_train = 14
        train_idx, val_idx = idx[:n_train], idx[n_train:]
        return x[train_idx], y[train_idx], x[val_idx], y[val_idx]

    def scene_06(self):
        xt, yt, xv, yv = self.scene6_data()
        degrees = list(range(1, 8))
        val_errors, train_errors = [], []
        for d in degrees:
            coef = np.polyfit(xt, yt, d)
            val_errors.append(float(np.mean((np.polyval(coef, xv) - yv) ** 2)))
            train_errors.append(float(np.mean((np.polyval(coef, xt) - yt) ** 2)))

        title = Text("Why Training-Validation Split Works", font_size=32).to_edge(UP, buff=0.4)
        subtitle = MathTex(
            r"\text{Ground truth: } y = 0.15x^3 - 0.4x^2 - 0.6x + 2", font_size=26, color=GREY_B
        ).next_to(title, DOWN, buff=0.2)

        # NumberLine/Axes' actual param is `tip_height` (not `tip_length`,
        # which is silently ignored) -- confirmed via introspection that the
        # previous key left the real tip length stuck at manim's 0.35
        # default while only width shrank, producing a long thin spike.
        tip_cfg = {"include_ticks": False, "tip_height": 0.1, "tip_width": 0.1}
        axes = Axes(
            x_range=[-3.3, 3.3, 1],
            y_range=[-8, 8, 4],
            x_length=6.2,
            y_length=4.6,
            axis_config=tip_cfg,
        ).move_to(LEFT * 3.4 + DOWN * 0.9)
        train_dots = VGroup(*[Dot(axes.coords_to_point(x, y), color=GREY_B, radius=0.06) for x, y in zip(xt, yt)])
        val_dots = VGroup(*[Dot(axes.coords_to_point(x, y), color=GREY_B, radius=0.06) for x, y in zip(xv, yv)])

        legend_train = VGroup(Dot(color=TRAIN_COLOR), Text("Training Data", font_size=18)).arrange(RIGHT, buff=0.15)
        legend_val = VGroup(Dot(color=VALIDATION_COLOR), Text("Validation Data", font_size=18)).arrange(RIGHT, buff=0.15)
        legend = VGroup(legend_train, legend_val).arrange(DOWN, buff=0.2, aligned_edge=LEFT).next_to(axes, UP, buff=0.15).align_to(axes, LEFT)

        err_axes = Axes(
            x_range=[0, 7.5, 1],
            y_range=[0, 3, 1],
            x_length=4.8,
            y_length=4.6,
            axis_config=tip_cfg,
        ).move_to(RIGHT * 3.8 + DOWN * 0.9)
        err_axes.get_x_axis().add_numbers([1, 2, 3, 4, 5, 6, 7], font_size=16)
        err_title = Text("Training / Validation Error", font_size=22, color=YELLOW).next_to(err_axes, UP, buff=0.2)
        deg_label = err_axes.get_x_axis_label(Text("Degree", font_size=18), edge=RIGHT, direction=RIGHT)

        # Sits in the chart's empty upper-right corner (errors stay well
        # below this height for every degree) so it doesn't compete with
        # err_title for space.
        err_legend_train = VGroup(
            Dot(color=TRAIN_COLOR, radius=0.05), Text("Training Error", font_size=14)
        ).arrange(RIGHT, buff=0.12)
        err_legend_val = VGroup(
            Dot(color=VALIDATION_COLOR, radius=0.05), Text("Validation Error", font_size=14)
        ).arrange(RIGHT, buff=0.12)
        err_legend = VGroup(err_legend_train, err_legend_val).arrange(DOWN, buff=0.12, aligned_edge=LEFT)
        err_legend.move_to(err_axes.c2p(6.0, 2.6))

        # Timing is keyed to where "third-degree polynomial", "green", and
        # "yellow" actually fall in the ~21.8s clip: dots appear neutral grey
        # while the data-generation process is described, then pick up their
        # train/validation color right as each word is spoken.
        with self.voiceover(
            text=(
                "Here's why training-validation split works so well against "
                "overfitting. As an example, imagine you are trying to fit data "
                "that are generated by a third-degree polynomial, and you "
                "progressively try polynomial models with higher degrees. Suppose "
                "the green data points are training data for model training and "
                "yellow are validation data for model evaluation."
            )
        ) as tracker:
            self.play(Write(title), run_time=1.2)
            self.wait(9.0)
            self.play(Write(subtitle), run_time=1.3)  # "...third-degree polynomial"
            self.play(Create(axes), run_time=1.3)
            self.play(FadeIn(train_dots, lag_ratio=0.08), FadeIn(val_dots, lag_ratio=0.08), run_time=1.0)
            self.wait(1.2)
            self.play(train_dots.animate.set_color(TRAIN_COLOR), FadeIn(legend_train), run_time=1.0)  # "green..."
            self.wait(3.0)
            self.play(val_dots.animate.set_color(VALIDATION_COLOR), FadeIn(legend_val), run_time=1.0)  # "yellow..."
            self.wait(tracker.get_remaining_duration())

        curve = None
        val_err_dots, val_err_lines = VGroup(), VGroup()
        train_err_dots, train_err_lines = VGroup(), VGroup()

        def fit_curve(d):
            coef = np.polyfit(xt, yt, d)
            return axes.plot(lambda x: np.polyval(coef, x), x_range=[-3.05, 3.05], color=RED, use_smoothing=False)

        def reveal_degree(d, curve_run_time, point_run_time):
            nonlocal curve
            new_curve = fit_curve(d)
            if curve is None:
                curve = new_curve
                self.play(Create(curve), run_time=curve_run_time)
            else:
                self.play(Transform(curve, new_curve), run_time=curve_run_time)

            val_pt = Dot(err_axes.coords_to_point(d, val_errors[d - 1]), color=VALIDATION_COLOR, radius=0.06)
            train_pt = Dot(err_axes.coords_to_point(d, train_errors[d - 1]), color=TRAIN_COLOR, radius=0.06)
            anims = [FadeIn(val_pt), FadeIn(train_pt)]
            if len(val_err_dots) > 0:
                val_err_lines.add(Line(val_err_dots[-1].get_center(), val_pt.get_center(), color=VALIDATION_COLOR, stroke_width=3))
                train_err_lines.add(Line(train_err_dots[-1].get_center(), train_pt.get_center(), color=TRAIN_COLOR, stroke_width=3))
                anims += [Create(val_err_lines[-1]), Create(train_err_lines[-1])]
            self.play(*anims, run_time=point_run_time)
            val_err_dots.add(val_pt)
            train_err_dots.add(train_pt)

        with self.voiceover(
            text=(
                "As the model becomes more complex, having higher and higher "
                "degrees, pay attention to the change of \"Validation Error\", "
                "which is a metric of how closely the model fits the validation data."
                "You can see that \"Validation Error\" decreases at first as the "
                "polynomial degree increases from 1 to 3, but beyond third-degree, "
                "further increasing the polynomial degree start to inflate "
                "\"Validation Error\", which is a sign of overfitting."
            )
        ) as tracker:
            self.play(Create(err_axes), Write(err_title), Write(deg_label), run_time=1.5)
            self.play(FadeIn(err_legend), run_time=0.7)
            self.wait(0.1)
            for d in [1, 2, 3, 4, 5, 6, 7]:
                reveal_degree(d, 1.0, 0.6)
                self.wait(0.3)
            self.wait(tracker.get_remaining_duration())

        best_idx = int(np.argmin(val_errors))
        best_degree = degrees[best_idx]
        best_dot = val_err_dots[best_idx]
        best_curve = fit_curve(best_degree)
        marker = Circle(radius=0.18, color=YELLOW, stroke_width=3).move_to(best_dot.get_center())
        best_label = Text(f"Best: Degree {best_degree}", font_size=18, color=YELLOW).next_to(marker, UP, buff=0.2).shift(RIGHT * 0.75)

        with self.voiceover(
            text=(
                "So, by monitoring model's performance on the validation data and "
                "select a model that achieves advantageous validation performance, "
                "we can effectively mitigate the risk of overfitting. Notice that "
                "training error keeps declining as the model grows more complex -- "
                "that's exactly why relying on training error alone would mislead "
                "us into picking an overly complex, overfit model. Validation "
                "error is what actually tells us when we've gone too far."
            )
        ) as tracker:
            self.play(Transform(curve, best_curve), run_time=1.5)
            self.play(Create(marker), FadeIn(best_label, shift=UP * 0.15), run_time=1.5)
            self.wait(tracker.get_remaining_duration())

        self.wait()
        self.play(
            FadeOut(title), FadeOut(subtitle), FadeOut(axes), FadeOut(train_dots), FadeOut(val_dots), FadeOut(legend),
            FadeOut(err_axes), FadeOut(err_title), FadeOut(err_legend), FadeOut(deg_label), FadeOut(curve),
            FadeOut(val_err_dots), FadeOut(val_err_lines), FadeOut(train_err_dots), FadeOut(train_err_lines),
            FadeOut(marker), FadeOut(best_label),
        )


class Scene06(VoiceoverScene, Scene06Mixin):
    """Standalone preview: manim -pql scene_06.py Scene06"""

    def construct(self):
        self.set_speech_service(get_speech_service())
        self.scene_06()
